name: simple-chat

services:
  redis-instance:
    image: redis:8.4-alpine

  app-server:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - .:/app
